- name: debug run_commands_user
  debug:
    msg: "run_commands_user: {{ run_commands_user }}"

- name: check normal user
  debug: 
    msg: "{{ ansible_user_id }}"

- name: check user with run_commands_user with become true
  become: true
  become_user: "{{ run_commands_user }}"
  command: 
    msg: "whoami"
  register: whoami

- name: check user with run_commands_user
  debug: 
    msg: "{{ whoami }}"

